#!/usr/bin/env python3
"""Automated FlowKit payload validation script.

Validates that all project, character, video, scene, and batch payloads generated by the
directing engine conform strictly to FlowKit API Pydantic V2 schemas and match live server specs.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any

# Ensure project root is in sys.path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.director.character import build_default_characters
from src.director.director import StoryDirector
from src.render_client.adapter import FlowKitPayloadAdapter
from src.render_client.models import (
    FlowKitCharacterCreate,
    FlowKitNarrateVideoRequest,
    FlowKitProjectCreate,
    FlowKitRequestCreate,
    FlowKitSceneCreate,
    FlowKitSceneUpdate,
    FlowKitVideoCreate,
)
from src.models import EpisodeManifest

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger("validate_flowkit_payloads")


def validate_manifest_payloads(
    manifest: EpisodeManifest,
    material: str = "realistic",
    live_url: str | None = None,
    verbose: bool = False,
) -> tuple[bool, dict[str, Any]]:
    """Runs complete validation suite on all FlowKit payloads derived from manifest."""
    report: dict[str, Any] = {
        "valid": True,
        "payloads_checked": 0,
        "errors": [],
        "summary": {},
    }

    print(f"\n{'='*70}")
    print(f"FlowKit Payload Validation Suite: {manifest.title} (Ep {manifest.episode_num})")
    print(f"{'='*70}\n")

    # 1. Validate Project Payload
    try:
        project_payload = FlowKitPayloadAdapter.to_project_payload(
            manifest=manifest,
            material=material,
            allow_music=False,
            allow_voice=True,
        )
        # Re-validate with strict schema
        validated_project = FlowKitProjectCreate.model_validate(project_payload.model_dump())
        report["payloads_checked"] += 1
        report["summary"]["project"] = validated_project.name
        print(f"[PASS] FlowKitProjectCreate: '{validated_project.name}' (material: {validated_project.material})")
        if verbose:
            print(json.dumps(validated_project.model_dump(), indent=2))
    except Exception as exc:
        report["valid"] = False
        report["errors"].append(f"FlowKitProjectCreate failed: {exc}")
        print(f"[FAIL] FlowKitProjectCreate: {exc}")

    # 2. Validate Character Payloads
    char_count = 0
    try:
        char_payloads = FlowKitPayloadAdapter.to_character_payloads(manifest.character_profiles)
        for char_p in char_payloads:
            validated_char = FlowKitCharacterCreate.model_validate(char_p.model_dump())
            char_count += 1
            report["payloads_checked"] += 1
            print(f"[PASS] FlowKitCharacterCreate: '{validated_char.name}' (type: {validated_char.entity_type})")
        report["summary"]["characters_validated"] = char_count
    except Exception as exc:
        report["valid"] = False
        report["errors"].append(f"FlowKitCharacterCreate failed: {exc}")
        print(f"[FAIL] FlowKitCharacterCreate: {exc}")

    # 3. Validate Video Container Payload
    dummy_project_id = "proj_val_001"
    try:
        video_payload = FlowKitPayloadAdapter.to_video_payload(
            manifest=manifest,
            project_id=dummy_project_id,
            orientation="VERTICAL",
        )
        validated_video = FlowKitVideoCreate.model_validate(video_payload.model_dump())
        report["payloads_checked"] += 1
        report["summary"]["video"] = validated_video.title
        print(f"[PASS] FlowKitVideoCreate: '{validated_video.title}' (orientation: {validated_video.orientation})")
    except Exception as exc:
        report["valid"] = False
        report["errors"].append(f"FlowKitVideoCreate failed: {exc}")
        print(f"[FAIL] FlowKitVideoCreate: {exc}")

    # 4. Validate Scene Payloads (Two-Step Initialization)
    dummy_video_id = "vid_val_001"
    scene_count = 0
    try:
        scene_pairs = FlowKitPayloadAdapter.to_scene_payloads(manifest, video_id=dummy_video_id)
        for idx, (scene_create, narrator_text) in enumerate(scene_pairs):
            # Step 1: Validate FlowKitSceneCreate
            validated_scene = FlowKitSceneCreate.model_validate(scene_create.model_dump())
            report["payloads_checked"] += 1

            # Step 2: Validate FlowKitSceneUpdate (narrator_text)
            update_payload = FlowKitSceneUpdate(narrator_text=narrator_text)
            validated_update = FlowKitSceneUpdate.model_validate(update_payload.model_dump())
            report["payloads_checked"] += 1
            scene_count += 1

            words = len(narrator_text.split()) if narrator_text else 0
            print(
                f"[PASS] Scene {idx}: SceneCreate OK | SceneUpdate (narrator_text: {words} words) OK"
            )
        report["summary"]["scenes_validated"] = scene_count
    except Exception as exc:
        report["valid"] = False
        report["errors"].append(f"Scene validation failed: {exc}")
        print(f"[FAIL] Scene validation: {exc}")

    # 5. Validate Generation Batch Requests
    dummy_scene_ids = [f"scene_val_{i}" for i in range(len(manifest.scenes))]
    try:
        img_reqs = FlowKitPayloadAdapter.to_batch_requests(
            scene_ids=dummy_scene_ids,
            project_id=dummy_project_id,
            video_id=dummy_video_id,
            req_type="GENERATE_IMAGE",
        )
        for r in img_reqs:
            FlowKitRequestCreate.model_validate(r.model_dump())
            report["payloads_checked"] += 1
        print(f"[PASS] Batch Request (GENERATE_IMAGE): {len(img_reqs)} requests validated")

        vid_reqs = FlowKitPayloadAdapter.to_batch_requests(
            scene_ids=dummy_scene_ids,
            project_id=dummy_project_id,
            video_id=dummy_video_id,
            req_type="GENERATE_VIDEO",
        )
        for r in vid_reqs:
            FlowKitRequestCreate.model_validate(r.model_dump())
            report["payloads_checked"] += 1
        print(f"[PASS] Batch Request (GENERATE_VIDEO): {len(vid_reqs)} requests validated")
    except Exception as exc:
        report["valid"] = False
        report["errors"].append(f"Batch request validation failed: {exc}")
        print(f"[FAIL] Batch request validation: {exc}")

    # 6. Validate Narration Request
    try:
        narr_payload = FlowKitPayloadAdapter.to_narrate_payload(
            project_id=dummy_project_id,
            orientation="VERTICAL",
            mix=True,
            sfx_volume=0.4,
        )
        validated_narr = FlowKitNarrateVideoRequest.model_validate(narr_payload.model_dump())
        report["payloads_checked"] += 1
        report["summary"]["narration"] = "VALID"
        print(f"[PASS] FlowKitNarrateVideoRequest: OK (speed: {validated_narr.speed}, sfx_vol: {validated_narr.sfx_volume})")
    except Exception as exc:
        report["valid"] = False
        report["errors"].append(f"FlowKitNarrateVideoRequest failed: {exc}")
        print(f"[FAIL] FlowKitNarrateVideoRequest: {exc}")

    # 7. Optional Live Service Verification
    if live_url:
        print(f"\n--- Checking Live FlowKit Service at {live_url} ---")
        try:
            import httpx
            with httpx.Client(base_url=live_url.rstrip("/"), timeout=10.0) as client:
                # Check status
                status_res = client.get("/flow/status")
                if status_res.status_code == 200:
                    status_json = status_res.json()
                    print(f"[LIVE] FlowKit status: connected={status_json.get('connected')}, transport={status_json.get('transport')}")
                else:
                    print(f"[LIVE WARNING] /flow/status returned HTTP {status_res.status_code}")

                # Verify material is recognized
                mat_res = client.get("/materials")
                if mat_res.status_code == 200:
                    materials = [m["id"] for m in mat_res.json()]
                    if material in materials:
                        print(f"[LIVE] Material '{material}' confirmed in live materials registry ({len(materials)} available)")
                    else:
                        err = f"Material '{material}' NOT found in live materials: {materials}"
                        report["valid"] = False
                        report["errors"].append(err)
                        print(f"[LIVE FAIL] {err}")
        except Exception as exc:
            print(f"[LIVE NOTICE] Could not query live FlowKit service: {exc}")

    print(f"\n{'='*70}")
    status_str = "SUCCESS" if report["valid"] else "FAILED"
    print(f"Validation Result: {status_str} ({report['payloads_checked']} payloads checked)")
    if report["errors"]:
        print("Errors encountered:")
        for err in report["errors"]:
            print(f"  - {err}")
    print(f"{'='*70}\n")

    return report["valid"], report


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate FlowKit Payloads for Shorts Content Engine")
    parser.add_argument("--manifest", type=str, help="Path to JSON EpisodeManifest file")
    parser.add_argument("--material", type=str, default="realistic", help="Material style ID")
    parser.add_argument("--live", action="store_true", help="Perform live service cross-validation")
    parser.add_argument("--live-url", type=str, default="http://127.0.0.1:8100/api", help="FlowKit API base URL")
    parser.add_argument("--verbose", action="store_true", help="Print detailed JSON payloads")
    args = parser.parse_args()

    if args.manifest:
        with open(args.manifest, "r", encoding="utf-8") as f:
            manifest_data = json.load(f)
        manifest = EpisodeManifest.model_validate(manifest_data)
    else:
        # Generate canonical episode for validation
        characters = build_default_characters()
        from src.models import SeriesState
        series_state = SeriesState(
            series_id="cyber_noir",
            title="The Obsidian Directive",
            genre="Sci-Fi Cyberpunk Noir",
            premise="Detective Vance enters the neon rain-soaked alley where a murdered android holds a quantum cipher.",
            characters={c.character_id: c for c in characters},
        )
        director = StoryDirector()
        manifest = director.direct_episode(
            series_state=series_state,
            episode_num=1,
            target_duration=45.0,
        )

    live_target = args.live_url if args.live else None
    success, _ = validate_manifest_payloads(
        manifest=manifest,
        material=args.material,
        live_url=live_target,
        verbose=args.verbose,
    )
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
